### ISSUE TITLE
Submission Issue #3 - Allowing Direct File Access to plugin files

### ISSUE THREAD

**Issue by bhubbard** [imFORZA/wp-listings-pro#145]
Direct file access is when someone directly queries your file. This can be done by simply entering the complete path to the file in the URL bar of the browser but can also be done by doing a POST request directly to the file. For files that only contain a PHP class the risk of something funky happening when directly accessed is pretty small. For files that contain procedural code, functions and function calls, the chance of security risks is a lot bigger.

You can avoid this by putting this code at the top of all php files:

```php
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly
```

**Comment by bhubbard** [comment]
I gave this a first pass, but give it one more to make sure we got every file.

**Comment by bradleymoore111** [comment]
I don't see anymore, I think you got them.
