### ISSUE TITLE
Issues setting Featured Images

### ISSUE THREAD

**Issue by bhubbard** [imFORZA/wp-listings-pro#174]
This plugin is having issue, as I am not able to select featured images on any page or post once this page is installed.. I am not able to set featured image on any image or for any agent. First I thought it must be conflicting with some other plugin but after complete check.. & installing on another fresh wordpress setup I found that this plugin is having issue. 

Reported by Glenn

**Comment by sfgarza** [comment]
It looks like the featured image is set properly when pulled from IDX, but wont work when manually setting it.

**Comment by sfgarza** [comment]
Also confirming Glenns observation, this affects featured images for all post types while the plugin is active. I would consider this a high priority

**Comment by sfgarza** [comment]
I've disabled JS and tried commenting out a bunch of code, but i still cant find the culprit so far. @bradleymoore111 If you can please look into this issue as well that would be greatly appreciated since this is a high priority issue that affects a core functionality

**Comment by sfgarza** [comment]
Not sure if its related to the same issue, but this blank image appears in the upload gallery when selecting a featured image. It dissapears once the plugin is deactivated

<img width="1265" alt="edit_listing_ _wp-listings-pro_ _wordpress" src="https://cloud.githubusercontent.com/assets/8662253/26708097/75b480fe-46fe-11e7-9e75-2495629731a8.png">
